[packages]
neovim = {
  github = "neovim/neovim",
  asset_pattern = "nvim-linux-x86_64.appimage",
  version = "stable",
  binaries = [
    { source = "neovim", link_as = "nvim" }
  ]
}
ripgrep = {
  github = "BurntSushi/ripgrep",
  asset_pattern = "ripgrep-*-x86_64-unknown-linux-musl.tar.gz"
}
tmux = {
  github = "tmux/tmux-builds",
  asset_pattern = "tmux-*-linux-x86_64.tar.gz"
}
# lazygit = {
#   version = "*",
#   repo = "soarpkgs"
# }
# fd = {
#   version = "*",
#   repo = "soarpkgs"
# }
# zoxide = {
#   version = "*",
#   repo = "soarpkgs"
# }
# bat = {
#   version = "*",
#   repo = "soarpkgs"
# }
# eza = {
#   version = "*",
#   repo = "soarpkgs"
# }
